// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: todo_service.proto

package todo_service_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_todo_service_proto protoreflect.FileDescriptor

const file_todo_service_proto_rawDesc = "" +
	"\n" +
	"\x12todo_service.proto\x12\ftodo_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"todo.proto2\xb0\x02\n" +
	"\vTodoService\x12O\n" +
	"\n" +
	"CreateTodo\x12\x1f.todo_service.CreateTodoRequest\x1a .todo_service.CreateTodoResponse\x12B\n" +
	"\n" +
	"GetAllTodo\x12\x16.google.protobuf.Empty\x1a\x1c.todo_service.GetAllResponse\x12E\n" +
	"\n" +
	"DeleteTodo\x12\x1f.todo_service.DeleteTodoRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\n" +
	"UpdateTodo\x12\x1f.todo_service.UpdateTodoRequest\x1a\x16.google.protobuf.EmptyB\x15Z\x13./todo_service_grpcb\x06proto3"

var file_todo_service_proto_goTypes = []any{
	(*CreateTodoRequest)(nil),  // 0: todo_service.CreateTodoRequest
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
	(*DeleteTodoRequest)(nil),  // 2: todo_service.DeleteTodoRequest
	(*UpdateTodoRequest)(nil),  // 3: todo_service.UpdateTodoRequest
	(*CreateTodoResponse)(nil), // 4: todo_service.CreateTodoResponse
	(*GetAllResponse)(nil),     // 5: todo_service.GetAllResponse
}
var file_todo_service_proto_depIdxs = []int32{
	0, // 0: todo_service.TodoService.CreateTodo:input_type -> todo_service.CreateTodoRequest
	1, // 1: todo_service.TodoService.GetAllTodo:input_type -> google.protobuf.Empty
	2, // 2: todo_service.TodoService.DeleteTodo:input_type -> todo_service.DeleteTodoRequest
	3, // 3: todo_service.TodoService.UpdateTodo:input_type -> todo_service.UpdateTodoRequest
	4, // 4: todo_service.TodoService.CreateTodo:output_type -> todo_service.CreateTodoResponse
	5, // 5: todo_service.TodoService.GetAllTodo:output_type -> todo_service.GetAllResponse
	1, // 6: todo_service.TodoService.DeleteTodo:output_type -> google.protobuf.Empty
	1, // 7: todo_service.TodoService.UpdateTodo:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todo_service_proto_init() }
func file_todo_service_proto_init() {
	if File_todo_service_proto != nil {
		return
	}
	file_todo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_service_proto_rawDesc), len(file_todo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_service_proto_goTypes,
		DependencyIndexes: file_todo_service_proto_depIdxs,
	}.Build()
	File_todo_service_proto = out.File
	file_todo_service_proto_goTypes = nil
	file_todo_service_proto_depIdxs = nil
}
